/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.reorg.challenge.weather.data.aggregator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
}
