/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.reorg.challenge.weather.data.aggregator;

import com.reorg.challenge.weather.data.aggregator.service.WeatherStatisticsService;

import java.io.File;

public class Main {

    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("A file name location must be provided!");
            System.exit(-1);
        }

        var file = new File(args[0]);
        if (!file.exists()) {
            System.err.println("The file provided does not exist!");
            System.exit(-1);
        }

        WeatherStatisticsService.printStatistics(file);
    }
}
